import { motion } from 'framer-motion';

import agency01 from '@/assets/gallery/agency-01-habit.png';
import agency02 from '@/assets/gallery/agency-02-coach.png';
import agency03 from '@/assets/gallery/agency-03-map.png';
import agency04 from '@/assets/gallery/agency-04-subs.png';
import agency05 from '@/assets/gallery/agency-05-water.png';
import agency06 from '@/assets/gallery/agency-06-sugar.png';
import agency07 from '@/assets/gallery/agency-07-aura.png';
import agency08 from '@/assets/gallery/agency-08-scribe.png';
import agency09 from '@/assets/gallery/agency-09-trainer.png';
import agency10 from '@/assets/gallery/agency-10-stackr.png';

const GALLERY_ITEMS = [
    { id: 1, title: 'HabitForge', style: 'Dark & Vibrant', src: agency01 },
    { id: 2, title: 'Mental Model', style: 'Premium Editorial', src: agency02 },
    { id: 3, title: 'Zenly Clone', style: 'Playful 3D', src: agency03 },
    { id: 4, title: 'Recur', style: 'Neon Tech', src: agency04 },
    { id: 5, title: 'Water Tracker', style: 'Friendly Mascot', src: agency05 },
    { id: 6, title: 'SugarBreak', style: 'Cinematic Motivation', src: agency06 },
    { id: 7, title: 'Aura Assistant', style: 'Soft 3D Pastel', src: agency07 },
    { id: 8, title: 'Scribe AI', style: 'Clean Corporate', src: agency08 },
    { id: 9, title: 'AI Trainer', style: 'High Energy Sport', src: agency09 },
    { id: 10, title: 'Stackr', style: 'Bold Brutalist', src: agency10 },
];

export const Gallery = () => {
    return (
        <section id="examples" className="py-24 bg-background relative overflow-hidden border-t border-border">
            <div className="container mx-auto px-6 mb-16 text-center">
                <h2 className="text-4xl md:text-5xl font-black tracking-tight text-foreground mb-6">
                    Outputs that rival top agencies.
                </h2>
                <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
                    Explore the sheer quality and variety of styles generated by our Consistency Engine.
                </p>
            </div>

            {/* Infinite Horizontal Marquee */}
            <div className="relative w-full flex overflow-hidden">
                {/* Left/Right Fades */}
                <div className="absolute top-0 bottom-0 left-0 w-32 bg-gradient-to-r from-background to-transparent z-10 pointer-events-none" />
                <div className="absolute top-0 bottom-0 right-0 w-32 bg-gradient-to-l from-background to-transparent z-10 pointer-events-none" />

                <motion.div
                    className="flex gap-6 px-6"
                    animate={{ x: [0, -3000] }}
                    transition={{ repeat: Infinity, ease: "linear", duration: 50 }}
                >
                    {[...GALLERY_ITEMS, ...GALLERY_ITEMS].map((item, i) => (
                        <div
                            key={`${item.id}-${i}`}
                            className="relative w-[320px] md:w-[480px] aspect-video rounded-2xl overflow-hidden group flex-shrink-0 cursor-pointer border border-border bg-card/50"
                        >
                            <img 
                                src={item.src} 
                                alt={item.title} 
                                className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" 
                            />

                            <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-6">
                                <div>
                                    <h4 className="text-white font-bold text-lg">{item.title}</h4>
                                    <span className="text-white/80 text-sm font-medium">{item.style}</span>
                                </div>
                            </div>
                        </div>
                    ))}
                </motion.div>
            </div>
        </section>
    );
};
