import { motion } from 'framer-motion';

import agency01 from '@/assets/gallery/agency-01-habit.png';
import agency02 from '@/assets/gallery/agency-02-coach.png';
import agency03 from '@/assets/gallery/agency-03-map.png';
import agency04 from '@/assets/gallery/agency-04-subs.png';
import agency05 from '@/assets/gallery/agency-05-water.png';
import agency06 from '@/assets/gallery/agency-06-sugar.png';
import agency07 from '@/assets/gallery/agency-07-aura.png';
import agency08 from '@/assets/gallery/agency-08-scribe.png';
import agency09 from '@/assets/gallery/agency-09-trainer.png';
import agency10 from '@/assets/gallery/agency-10-stackr.png';
import agency11 from '@/assets/gallery/agency-11-trainer-ai.png';
import agency12 from '@/assets/gallery/agency-12-stackr-yellow.png';
import agency13 from '@/assets/gallery/agency-13-vow.png';
import agency14 from '@/assets/gallery/agency-14-rpg.png';
import agency15 from '@/assets/gallery/agency-15-cram.png';
import agency16 from '@/assets/gallery/agency-16-adblock.png';
import agency17 from '@/assets/gallery/agency-17-drift.png';
import agency18 from '@/assets/gallery/agency-18-coaching.png';
import agency19 from '@/assets/gallery/agency-19-tape.png';
import agency20 from '@/assets/gallery/agency-20-solo.png';
import agency21 from '@/assets/gallery/agency-21-minddrop.png';
import agency22 from '@/assets/gallery/agency-22-mealplan.png';
import agency23 from '@/assets/gallery/agency-23-vault.jpeg';
import agency24 from '@/assets/gallery/agency-24-linguaflow.png';
import agency25 from '@/assets/gallery/agency-25-nestle.png';
import agency26 from '@/assets/gallery/agency-26-lifeplan.png';
import agency27 from '@/assets/gallery/agency-27-foxlearn.png';

const GALLERY_ITEMS = [
    { id: 1, title: 'HabitForge', style: 'Dark & Vibrant', src: agency01 },
    { id: 2, title: 'Mental Model', style: 'Premium Editorial', src: agency02 },
    { id: 3, title: 'Zenly Clone', style: 'Playful 3D', src: agency03 },
    { id: 4, title: 'Recur', style: 'Neon Tech', src: agency04 },
    { id: 5, title: 'Water Tracker', style: 'Friendly Mascot', src: agency05 },
    { id: 6, title: 'SugarBreak', style: 'Cinematic Motivation', src: agency06 },
    { id: 7, title: 'Aura Assistant', style: 'Soft 3D Pastel', src: agency07 },
    { id: 8, title: 'Scribe AI', style: 'Clean Corporate', src: agency08 },
    { id: 9, title: 'AI Trainer', style: 'High Energy Sport', src: agency09 },
    { id: 10, title: 'Stackr', style: 'Bold Brutalist', src: agency10 },
    { id: 11, title: 'FitMax AI', style: 'Sport & Mascot', src: agency11 },
    { id: 12, title: 'Stackr Cashback', style: 'Yellow Bold', src: agency12 },
    { id: 13, title: 'Vow', style: 'Luxury Elegant', src: agency13 },
    { id: 14, title: 'LinguaQuest', style: 'RPG Gaming', src: agency14 },
    { id: 15, title: 'Cram', style: 'Minimal Neon', src: agency15 },
    { id: 16, title: 'AdBlock Pro', style: 'Dark Tech', src: agency16 },
    { id: 17, title: 'Drift Sleep', style: 'Dark Ambient', src: agency17 },
    { id: 18, title: 'Syncy Coach', style: 'Organic Wellness', src: agency18 },
    { id: 19, title: 'Tape', style: 'Dark Warm', src: agency19 },
    { id: 20, title: 'Solo', style: 'Corporate Blue', src: agency20 },
    { id: 21, title: 'MindDrop', style: 'Dark Gold Premium', src: agency21 },
    { id: 22, title: 'MealFlow', style: 'Fresh Organic', src: agency22 },
    { id: 23, title: 'Vault', style: 'Finance Dark', src: agency23 },
    { id: 24, title: 'LinguaFlow', style: 'Gradient Vibrant', src: agency24 },
    { id: 25, title: 'Nestle Home', style: 'Editorial Minimal', src: agency25 },
    { id: 26, title: 'LifePlan', style: 'Warm Adventure', src: agency26 },
    { id: 27, title: 'FoxLearn', style: 'Kids Colorful', src: agency27 },
];

export const Gallery = () => {
    return (
        <section id="examples" className="py-24 bg-background relative overflow-hidden border-t border-border">
            <div className="container mx-auto px-6 mb-16 text-center">
                <h2 className="text-4xl md:text-5xl font-black tracking-tight text-foreground mb-6">
                    Outputs that rival top agencies.
                </h2>
                <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
                    Explore the sheer quality and variety of styles generated by our Consistency Engine.
                </p>
            </div>

            {/* Infinite Horizontal Marquee */}
            <div className="relative w-full flex overflow-hidden">
                {/* Left/Right Fades */}
                <div className="absolute top-0 bottom-0 left-0 w-32 bg-gradient-to-r from-background to-transparent z-10 pointer-events-none" />
                <div className="absolute top-0 bottom-0 right-0 w-32 bg-gradient-to-l from-background to-transparent z-10 pointer-events-none" />

                <motion.div
                    className="flex gap-6 px-6"
                    animate={{ x: [0, -6000] }}
                    transition={{ repeat: Infinity, ease: "linear", duration: 90 }}
                >
                    {[...GALLERY_ITEMS, ...GALLERY_ITEMS].map((item, i) => (
                        <div
                            key={`${item.id}-${i}`}
                            className="relative w-[320px] md:w-[480px] aspect-video rounded-2xl overflow-hidden group flex-shrink-0 cursor-pointer border border-border bg-card/50"
                        >
                            <img 
                                src={item.src} 
                                alt={item.title} 
                                className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" 
                            />

                            <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-6">
                                <div>
                                    <h4 className="text-white font-bold text-lg">{item.title}</h4>
                                    <span className="text-white/80 text-sm font-medium">{item.style}</span>
                                </div>
                            </div>
                        </div>
                    ))}
                </motion.div>
            </div>
        </section>
    );
};
