import { motion } from 'framer-motion';

const MOCK_GALLERY = [
    { id: 1, title: 'Neo Banking', color: 'from-blue-600 to-indigo-900', style: 'Dark & Sleek' },
    { id: 2, title: 'Fitness Tracker', color: 'from-emerald-500 to-teal-900', style: 'High Energy' },
    { id: 3, title: 'Crypto Wallet', color: 'from-violet-600 to-purple-900', style: 'Premium 3D' },
    { id: 4, title: 'Meditation App', color: 'from-amber-200 to-orange-500', style: 'Soft Minimal' },
    { id: 5, title: 'Food Delivery', color: 'from-rose-500 to-red-900', style: 'Bold & Punchy' },
    { id: 6, title: 'Travel Planner', color: 'from-cyan-400 to-blue-700', style: 'Clean & Bright' },
];

export const Gallery = () => {
    return (
        <section id="examples" className="py-24 bg-background relative overflow-hidden border-t border-border">
            <div className="container mx-auto px-6 mb-16 text-center">
                <h2 className="text-4xl md:text-5xl font-black tracking-tight text-foreground mb-6">
                    Outputs that rival top agencies.
                </h2>
                <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
                    Explore the sheer quality and variety of styles generated by our Consistency Engine.
                </p>
            </div>

            {/* Infinite Horizontal Marquee */}
            <div className="relative w-full flex overflow-hidden">
                {/* Left/Right Fades */}
                <div className="absolute top-0 bottom-0 left-0 w-32 bg-gradient-to-r from-background to-transparent z-10" />
                <div className="absolute top-0 bottom-0 right-0 w-32 bg-gradient-to-l from-background to-transparent z-10" />

                <motion.div
                    className="flex gap-6 px-6"
                    animate={{ x: [0, -2000] }}
                    transition={{ repeat: Infinity, ease: "linear", duration: 40 }}
                >
                    {[...MOCK_GALLERY, ...MOCK_GALLERY].map((item, i) => (
                        <div
                            key={`${item.id}-${i}`}
                            className="relative w-[280px] md:w-[320px] aspect-[4/3] rounded-2xl overflow-hidden group flex-shrink-0 cursor-pointer"
                        >
                            {/* Mock generated image using gradients for now */}
                            <div className={`absolute inset-0 bg-gradient-to-br ${item.color} opacity-80 group-hover:opacity-100 transition-opacity duration-500`} />

                            {/* Internal mock app screens */}
                            <div className="absolute inset-0 flex items-center justify-center gap-4 p-6 perspective-[1000px]">
                                <div className="w-[80px] h-[160px] bg-card/90 rounded-xl border border-border shadow-2xl rotate-y-[-10deg] rotate-z-[-5deg]" />
                                <div className="w-[90px] h-[180px] bg-card/90 rounded-xl border border-border shadow-2xl z-10" />
                                <div className="w-[80px] h-[160px] bg-card/90 rounded-xl border border-border shadow-2xl rotate-y-[10deg] rotate-z-[5deg]" />
                            </div>

                            <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-6">
                                <div>
                                    <h4 className="text-foreground font-bold text-lg">{item.title}</h4>
                                    <span className="text-muted-foreground text-sm">{item.style}</span>
                                </div>
                            </div>
                        </div>
                    ))}
                </motion.div>
            </div>
        </section>
    );
};
