import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });

export interface GenerateSlideOptions {
    prompt: string;
    referenceImages: { mimeType: string; data: string }[];
    aspectRatio?: string;
    imageSize?: string;
}

export interface GenerateSlideResult {
    imageBase64: string;
    text?: string;
}

/**
 * Generate a single screenshot slide using Gemini Nano Banana 2.
 * Accepts a text prompt + up to 14 reference images (base64).
 */
export async function generateSlide(options: GenerateSlideOptions): Promise<GenerateSlideResult> {
    const { prompt, referenceImages, aspectRatio = '9:16', imageSize = '2K' } = options;

    // Build contents array: text prompt + inline image data
    const contents: any[] = [{ text: prompt }];

    for (const img of referenceImages.slice(0, 14)) {
        contents.push({
            inlineData: {
                mimeType: img.mimeType,
                data: img.data,
            },
        });
    }

    const response = await ai.models.generateContent({
        model: 'gemini-3.1-flash-image-preview',
        contents,
        config: {
            responseModalities: ['TEXT', 'IMAGE'],
            imageConfig: {
                aspectRatio,
                imageSize,
            },
        } as any,
    });

    let imageBase64 = '';
    let text = '';

    if (response.candidates && response.candidates[0]) {
        for (const part of response.candidates[0].content!.parts!) {
            if ((part as any).text) {
                text += (part as any).text;
            } else if ((part as any).inlineData) {
                imageBase64 = (part as any).inlineData.data;
            }
        }
    }

    if (!imageBase64) {
        throw new Error('No image was generated by the model');
    }

    return { imageBase64, text: text || undefined };
}

export { ai };
